import { TrendingTopic } from '@/types';

export const TRENDING_TOPICS: TrendingTopic[] = [
  {
    id: 'youtube-trending',
    title: 'Músicas em alta agora no YouTube',
    category: 'youtube',
    engagement: 'Atualizado a cada hora',
    timeAgo: 'capturado há poucos minutos',
    source: 'YouTube Charts',
    link: 'https://charts.youtube.com/charts/TrendingVideos/br/RightNow',
    domain: 'charts.youtube.com',
    description: 'Visualize os clipes que explodiram no YouTube Brasil em tempo real.',
    previewImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    highlights: ['Música + vídeo', 'Brasil', 'Fonte oficial YouTube'],
  },
  {
    id: 'x-trends',
    title: 'Trending Topics do X em tempo real',
    category: 'x',
    engagement: 'Atualização minuto a minuto',
    timeAgo: 'fluxo ao vivo',
    source: 'Trends24',
    link: 'https://trends24.in/brazil/',
    domain: 'trends24.in',
    description: 'Monitore as hashtags e tópicos que dominam o X neste momento.',
    previewImage: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80',
    highlights: ['Hot topics', 'Tempo real', 'Cobertura nacional'],
  },
  {
    id: 'news-youtube',
    title: 'Breaking News direto do YouTube',
    category: 'news',
    engagement: 'Cobertura 24/7',
    timeAgo: 'últimos minutos',
    source: 'Band Jornalismo',
    link: 'https://www.youtube.com/channel/UCYfdidRxbB8Qhf0Nx7ioOYw',
    domain: 'youtube.com',
    description: 'Lives e destaques com as principais manchetes do dia em vídeo.',
    previewImage: 'https://images.unsplash.com/photo-1525182008055-f88b95ff7980?auto=format&fit=crop&w=1200&q=80',
    highlights: ['Notícias urgentes', 'Vídeo ao vivo', 'Cobertura nacional'],
  },
  {
    id: 'spotify-hits',
    title: 'Top músicas e charts do Spotify',
    category: 'spotify',
    engagement: 'Atualização diária',
    timeAgo: 'sincronizado hoje',
    source: 'Spotify Charts',
    link: 'https://charts.spotify.com/home',
    domain: 'charts.spotify.com',
    description: 'Acompanhe os rankings oficiais do Spotify e descubra novas faixas.',
    previewImage: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=80',
    highlights: ['Top 50 Brasil', 'Novas descobertas', 'Gêneros variados'],
  },
  {
    id: 'instagram-hashtags',
    title: 'Hashtags mais quentes para Instagram',
    category: 'instagramHashtags',
    engagement: 'Atualizado várias vezes ao dia',
    timeAgo: 'capturado agora',
    source: 'StarNgage',
    link: 'https://starngage.com/app/global/hashtags/top',
    domain: 'starngage.com',
    description: 'Encontre hashtags em ascensão para ampliar o alcance das suas postagens.',
    previewImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
    highlights: ['Descoberta orgânica', 'Rankings globais', 'Insights para criadores'],
  },
  {
    id: 'tiktok-videos',
    title: 'Trending videos do TikTok Brasil',
    category: 'tiktok',
    engagement: 'Atualização hora em hora',
    timeAgo: 'sincronizado agora',
    source: 'TikTok Creative Center',
    link: 'https://ads.tiktok.com/business/creativecenter/inspiration/popular/pc/pt',
    domain: 'ads.tiktok.com',
    description: 'Explore os vídeos com maior performance no TikTok brasileiro.',
    previewImage: 'https://images.unsplash.com/photo-1600488999015-997ef85f0c9b?auto=format&fit=crop&w=1200&q=80',
    highlights: ['Performance criativa', 'Insights de engajamento', 'Dados do TikTok'],
  },
  {
    id: 'tiktok-hashtags',
    title: 'Trending hashtags do TikTok',
    category: 'tiktokHashtags',
    engagement: 'Atualização constante',
    timeAgo: 'rastreamento ao vivo',
    source: 'TikTok Creative Center',
    link: 'https://ads.tiktok.com/business/creativecenter/inspiration/popular/hashtag/pc/pt',
    domain: 'ads.tiktok.com',
    description: 'Veja quais hashtags estão impulsionando campanhas virais agora mesmo.',
    previewImage: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
    highlights: ['Campanhas virais', 'Desafios ativos', 'Segmentação por nicho'],
  },
];
